### PR TITLE
Refactor tests to report errors clearly

### PR DESCRIPTION
**Pull request by Ygnas**
Closes: #400

### CODE REVIEW

**Comment by maleck13** [comment]
This looks a lot more informative now on failure. @mikenairn WDYT? I think this is a good approach for these types of errors

**Comment by mikenairn** [comment]
> This looks a lot more informative now on failure. @mikenairn WDYT? I think this is a good approach for these types of errors

Looks good to me. Returning errors makes sense. :+1:

**Comment by maleck13** [comment]
@Ygnas I think we can mark this as ready then I will merge

**Comment by Ygnas** [comment]
> @Ygnas I think we can mark this as ready then I will merge

Well there is more tests to be done.

**Comment by maleck13** [comment]
@Ygnas ah ok cool. Then I think the approach is good and lets covert the rest :) If you wanted to merge in several PRs that would also be fine to avoid potential conflicts and rebases?

**Review by maleck13 — APPROVED** [review]
/lgtm

**Pull request merged**
