### PR TITLE
fix perms around issuers

### PR DESCRIPTION
**Pull request by maleck13**
fix `pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.ClusterIssuer: unknown (get clusterissuers.cert-manager.io)`

### CODE REVIEW

**Comment by maleck13** [comment]
@mikenairn tested this locally and not seeing the error any more so looks good as the fix

**Comment by maleck13** [comment]
added a fix for `make deploy-policy-controller`

**Comment by mikenairn** [comment]
I'm not totally sure why we haven't seen this error before (e2e tests), but it does appear that when using a cached client you also need the watch perm to get a resource, so ....

/lgtm
/approve

**Pull request merged**
