### PR TITLE
Pin clusteradm to 0.5.1 release and ocm bundle to 0.10.0

### PR DESCRIPTION
**Pull request by roivaz**
* pin the version of clusteradm to 0.5.1
* pin the version of the ocm bunlde to 0.10.0

### CODE REVIEW

**Comment by david-martin** [comment]
Tried out locally.
Working, with 1 exception that I've reached out on slack about (both internal slack and ocm https://kubernetes.slack.com/archives/C01GE7YSUUF/p1685016272443249)
Happy to approve the change, but won't add an lgtm until someone else with an m1 mac has tried it to rule out the issue I'm seeing

/approve

**Comment by roivaz** [comment]
@david-martin pushed changes to pin clusteradm to 0.5.1 and the ocm bundle to 0.10.0. Seems to be the only combination that works currently. Can you give it a try?

**Comment by R-Lawton** [comment]
im not getting any issues but only one cluster is coming up when ives asked for multiple. Are any of ye seeing that?

**Pull request merged**
