### PR TITLE
waiting for deployments

### PR DESCRIPTION
**Pull request by laurafitzgerald**
Small pr to add wait for deployments

### CODE REVIEW

**Comment by makslion** [comment]
/lgtm

Looks good and after a bit of digging around don't see reasons/ways to make the `local-setup` path wait for those. I'll tag the #413 and [link](https://kubernetes.slack.com/archives/C05J0D0V525/p1691661539443489) the slack thread here so the person revisiting this logic would have an easier time finding out the reasoning behind the change.

**Comment by laurafitzgerald** [comment]
> /lgtm
> 
> Looks good and after a bit of digging around don't see reasons/ways to make the `local-setup` path wait for those. I'll tag the #413 and [link](https://kubernetes.slack.com/archives/C05J0D0V525/p1691661539443489) the slack thread here so the person revisiting this logic would have an easier time finding out the reasoning behind the change.

The wait is based on the components that are called by kustomize. so the kustomize we use is the quick-start ones. so there shouldn't be any variance on the waits between the two.

**Review by makslion — APPROVED** [review]

**Review by maleck13 — APPROVED** [review]

**Pull request merged**
